### ISSUE TITLE
Photo doesn't load on the main page

### ISSUE THREAD

**Issue by jinyoungbang** [jinyoungbang/Randoggo#2]
<img width="1440" alt="Screen Shot 2019-12-28 at 8 20 53 AM" src="https://user-images.githubusercontent.com/44107246/71535691-00260880-294b-11ea-8662-f3faeee23997.png">

**Comment by yoontsy2000** [comment]
Does MacOS handle directories differently?

**Comment by jinyoungbang** [comment]
Maybe, i can try fix it when i get back home

**Comment by jinyoungbang** [comment]
check index.html line 25 and try keep that consistent if possible
